export const departments = [
        {
          id: "101",
          name: "Department of Chinese Literature",
          short : "Chinese Literature",
          chinese_name : "中文系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=1",
          official_website_url: "https://chinese.nccu.edu.tw/",
          course_map_url:""
  
        },
        {
          id: "103",
          name: "Department of History",
          short : "History",
          chinese_name : "歷史系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=2",
          official_website_url: "https://history.nccu.edu.tw/",
        },
        {
          id: "104",
          name: "Department of Philosophy",
          short : "Philosophy",
          chinese_name : "哲學系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=3",
          official_website_url: "https://thinker.nccu.edu.tw/",
        },
        {
          id: "100",
          name: "College of Liberal Arts ",
          short : "College of Liberal Arts ",
          chinese_name : "文院學士",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=4",
          official_website_url: "https://la.nccu.edu.tw/",
        },
        {
          id: "158",
          name: "Graduate Institute of Taiwan History",
          short : "Graduate Institute of Taiwan History",
          chinese_name : "台史所 ",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
          official_website_url: "https://taiwan.nccu.edu.tw/",
          course_map_url:""
        },
        {
          id: "159",
          name: "Graduate Institute of Taiwanese Literature",
          short : "Graduate Institute of Taiwanese Literature",
          chinese_name : "台文所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
          official_website_url: "https://tailit.nccu.edu.tw/",
          course_map_url:""
        },
        {
          id: "156",
          name: "Graduate Institute of Religious Studies",
          short : "Graduate Institute of Religious Studies",
          chinese_name : "宗教所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=7",
          official_website_url: "https://religion.nccu.edu.tw/",
          course_map_url:""
        },
        {
          id: "155",
          name: "Graduate Institute of Library, Information and Archival Studies",
          short : "Graduate Institute of Library, Information and Archival Studies",
          chinese_name : "圖檔所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=8",
          official_website_url: "https://lias.nccu.edu.tw/",
          course_map_url:""
        },
        {
          id: "913",
          name: "E-learning Master Program of Library and Information Studies",
          short : "E-learning Master Program of Library and Information Studies",
          chinese_name : "圖資專",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=9",
          official_website_url: "https://elis.nccu.edu.tw/",
          course_map_url:""
        },
        {
          id: "912",
          name:"Master of Chinese Teaching",
          short : "Master of Chinese Teaching",
          chinese_name : "國教碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=9",
          official_website_url: "http://ctma.nccu.edu.tw/",
        },
        {
          id: "161",
          name: "Master's Program in Teaching Chinese as a Second Language",
          short : "Master's Program in Teaching Chinese as a Second Language",
          chinese_name : "華文碩程",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
          official_website_url: "https://tcsl.nccu.edu.tw/",
          course_map_url:""
        },
        {
          id: "160",
          name: "Doctor's Program in Teaching Chinese as a Second Language",
          short : "Doctor's Program in Teaching Chinese as a Second Language",
          chinese_name : "華文博",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=1",
          official_website_url: "https://tcsl.nccu.edu.tw/",
          course_map_url:""
        },
        {
          id: "102",
          name:"Department of Education",
          short : "Education",
          chinese_name : "教育系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
          official_website_url: "https://edu.nccu.edu.tw/",
        },
        {
          id: "900",
          name:"College of Education",
          short : "College of Education",
          chinese_name : "教院",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
          official_website_url: "https://educ.nccu.edu.tw/",
        },
        {
          id: "911",
          name:"Master of Education in School Administration",
          short : "Master of Education in School Administration",
          chinese_name : "學行碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
          official_website_url: "https://mesa.nccu.edu.tw/",
        },
        {
          id: "157",
          name:"Graduate Institute of Early Childhood Education",
          short : "Graduate Institute of Early Childhood Education",
          chinese_name : "幼教碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=7",
          official_website_url: "https://ece.nccu.edu.tw/",
        },
        {
          id: "171",
          name:"Graduate Institute of Educational Administration and Policy",
          short : "Graduate Institute of Educational Administration and Policy",
          chinese_name : "教政碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=8",
          official_website_url: "https://eap.nccu.edu.tw/",
        },
        {
          id: "202",
          name: "Department of Political Science",
          short : "Political Science",
          chinese_name : "政治系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=2",
          official_website_url: "https://politics.nccu.edu.tw/",
        },
        {
          id: "204",
          name: "Department of Sociology",
          short : "Sociology",
          chinese_name : "社會系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=3",
          official_website_url: "https://sociology.nccu.edu.tw/",
        },
        {
          id: "205",
          name: "Department of Public Finance",
          short : "Public Finance",
          chinese_name : "財政系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=4",
          official_website_url: "https://pf.nccu.edu.tw/",
        },
        {
          id: "206",
          name: "Department of Public Administration",
          short : "Public Administration",
          chinese_name : "公行系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
          official_website_url: "https://pa.nccu.edu.tw/",
        },
        {
          id: "207",
          name: "Department of Land Economics",
          short : "Land Economics",
          chinese_name : "地政系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
          official_website_url: "https://landeconomics.nccu.edu.tw/",
        },
        {
          id: "208",
          name: "Department of Economics",
          short : "Economics",
          chinese_name : "經濟系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=7",
          official_website_url: "https://econo.nccu.edu.tw/",
        },
        {
          id: "209",
          name: "Department of Ethnology",
          short : "Ethnology",
          chinese_name : "民族系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=8",
          official_website_url: "http://www.ethnos.nccu.edu.tw/institute.asp",
        },
        {
          id: "261",
          name: "Graduate Institute of Development Studies",
          short : "Graduate Institute of Development Studies",
          chinese_name : "國發所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=9",
          official_website_url: "http://www.ethnos.nccu.edu.tw/institute.asp",
        },
        {
          id: "262",
          name: "Graduate Institute of Labor Research",
          short : "Graduate Institute of Labor Research",
          chinese_name : "勞工所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
          official_website_url: "https://labour.nccu.edu.tw/",
        },
        {
          id: "264",
          name: "The Master Program of Land Economics",
          short : "The Master Program of Land Economics",
          chinese_name : "地政專",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=11",
          official_website_url: "safdsfsdfsdf",
        },
        {
          id: "267",
          name: "Masters Program in Land Policy and Environmental Planning for Indigenous Peoples",
          short : "Masters Program in Land Policy and Environmental Planning for Indigenous Peoples",
          chinese_name : "原碩專",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=12",
          official_website_url: "http://iland.nccu.edu.tw/",
        },
        {
          id: "264",
          name: "Graduate Institute of Social Work",
          short : "Graduate Institute of Social Work",
          chinese_name : "社工碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=13",
          official_website_url: "https://socialwork.nccu.edu.tw/",
        },
        {
          id: "266",
          name: "International Master's Program of Applied Economics and Social Development",
          short : "International Master's Program of Applied Economics and Social Development",
          chinese_name : "應社碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=14",
          official_website_url: "https://internationalprograms.nccu.edu.tw/home-imes/",
        },
        {
          id: "218",
          name: "Master of Eminent Public Administrators",
          short : "Master of Eminent Public Administrators",
          chinese_name : "行管碩/行國防/行領導",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=15",
          official_website_url: "https://mepa.nccu.edu.tw/",
        },
        {
          id: "926",
          name: "International Master's Program in Asia-Pacific Studies",
          short : "International Master's Program in Asia-Pacific Studies",
          chinese_name : "亞太碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=16",
          official_website_url: "safdsfsdfsdf",
        },
        {
          id: "265",
          name: "International Doctoral Program in Asia-Pacific Studies",
          short : "International Doctoral Program in Asia-Pacific Studies",
          chinese_name : "亞太博",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=17",
          official_website_url: "https://internationalprograms.nccu.edu.tw/home-idas/",
        },
        {
          id: "203",
          name:"Department of Diplomacy",
          short : "Diplomacy",
          chinese_name : "外交系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=18",
          official_website_url: "https://diplomacy.nccu.edu.tw/",
        },
        {
          id: "800",
          name: "College of International Affairs",
          short : "College of International Affairs",
          chinese_name : "國務院",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=19",
          official_website_url: "https://ocia.nccu.edu.tw/",
        },
        {
          id: "260",
          name: "Graduate Institute of East Asian Studies",
          short : "Graduate Institute of East Asian Studies",
          chinese_name : "東亞所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=20",
          official_website_url: "https://eastasia.nccu.edu.tw/",
        },
        {
          id: "206",
          name: "Master Program in Middle Eastern and Central Asian Studies",
          short : "Master Program in Middle Eastern and Central Asian Studies",
          chinese_name : "中東亞",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=21",
          official_website_url: "https://mecas.nccu.edu.tw/",
        },
        {
          id: "207",
          name: "Master Program in Strategic and International Studies",
          short : "Master Program in Strategic and International Studies",
          chinese_name : "外戰略",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=22",
          official_website_url: "https://diplomacy.nccu.edu.tw/PageDoc?fid=4848",
        },
        {
          id: "981",
          name: "Master Program in National Security and Mainland China Studies",
          short : "Master Program in National Security and Mainland China Studies",
          chinese_name : "國安碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=23",
          official_website_url: "https://ocia51113.nccu.edu.tw/",
        },
        {
          id: "861",
          name: "Master Program in Japan Studies",
          short : "Master Program in Japan Studies",
          chinese_name : "日本碩學程",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=24",
          official_website_url: "asdasdasdasd",
        },
        {
          id: "863",
          name: "Doctoral Program in Japan Studies",
          short : "Doctoral Program in Japan Studies",
          chinese_name : "日學博",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=25",
          official_website_url: "https://mpjs.nccu.edu.tw/",
        },
        {
          id: "301",
          name: "Department of International Business",
          short : "International Business",
          chinese_name : "國貿系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
          official_website_url: "https://ib.nccu.edu.tw/",
        },
        {
          id: "302",
          name: "Department of Money and Banking",
          short : "Money and Banking",
          chinese_name : "金融系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=4",
          official_website_url: "https://banking.nccu.edu.tw/",
        },
        {
          id: "303",
          name: "Department of Accounting",
          short : "Accounting",
          chinese_name : "會計系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=15",
          official_website_url: "https://acct.nccu.edu.tw/",
        },
        {
          id: "304",
          name: "Department of Statistics",
          short : "Statistics",
          chinese_name : "統計系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
          official_website_url: "",
        },
        {
          id: "305",
          name: "Department of Business Administration",
          short : "Business Administration",
          chinese_name : "企管系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=17",
          official_website_url: "http://www.ba.nccu.edu.tw/",
        },
        {
          id: "306",
          name: "Department of Management Information Systems",
          short : "Management Information Systems",
          chinese_name : "資管系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=18",
          official_website_url: "https://mis2.nccu.edu.tw/",
        },
        {
          id: "307",
          name: "Department of Finance",
          short : "Finance",
          chinese_name : "財管系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=19",
          official_website_url: "https://finance.nccu.edu.tw/",
        },
        {
          id: "308",
          name: "Department of Risk Management and Insurance",
          short : "Risk Management and Insurance",
          chinese_name : "風管系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=21",
          official_website_url: "https://rmi.nccu.edu.tw/",
        },
        {
          id: "300",
          name: "College of Commerce",
          short : "College of Commerce",
          chinese_name : "商院學士",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=22",
          official_website_url: "https://commerce.nccu.edu.tw/",
        },
        {
          id: "364",
          name: "Graduate Institute of Technology, Innovation and Intellectual Property Management",
          short : "Graduate Institute of Technology, Innovation and Intellectual Property Management",
          chinese_name : "科管智財所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=23",
          official_website_url: "https://tiipm.nccu.edu.tw/",
        },
        {
          id: "363",
          name: "Master of Business Administration Program",
          short : "Master of Business Administration Program",
          chinese_name : "企研碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=24",
          official_website_url: "https://mba.nccu.edu.tw/",
        },
        {
          id: "933",
          name: "International Master of Business Administration",
          short : "International Master of Business Administration",
          chinese_name : "國營碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=25",
          official_website_url: "https://imba.nccu.edu.tw/",
        },
        {
          id: "401",
          name: "Department of Journalism",
          short : "Journalism",
          chinese_name : "新聞系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=26",
          official_website_url: "",
        },
        {
          id: "402",
          name: "Department of Advertising",
          short : "Advertising",
          chinese_name : "廣告系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=28",
          official_website_url: "https://ad.nccu.edu.tw/",
        },
        {
          id: "403",
          name: "Department of Radio & Television",
          short : "Radio & Television",
          chinese_name : "廣電系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=29",
          official_website_url: "https://rtv.nccu.edu.tw/",
        },
        {
          id: "405",
          name: "Undeclared Major in College of Communication",
          short : "Undeclared Major in College of Communication",
          chinese_name : "傳院",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
          official_website_url: "https://comm.nccu.edu.tw/",
        },
        {
          id: "406",
          name: "College of Communication",
          short : "College of Communication",
          chinese_name : "傳播學程",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=11",
          official_website_url: "https://comm.nccu.edu.tw/",
        },
        {
          id: "462",
          name: "Graduate Program in  Digital Content and Technologies",
          short : "Graduate Program in  Digital Content and Technologies",
          chinese_name : "數位碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=12",
          official_website_url: "https://www.dct.nccu.edu.tw/",
        },
        {
          id: "464",
          name: "International Master's Program in International Communication Studies",
          short : "International Master's Program in International Communication Studies",
          chinese_name : "國傳碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=13",
          official_website_url: "https://imics.nccu.edu.tw/",
        },
        {
          id: "941",
          name: "M.A. Program in Communication",
          short : "M.A. Program in Communication",
          chinese_name : "傳在碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=14",
          official_website_url: "https://ema.comm.nccu.edu.tw/",
        },
        {
          id: "463",
          name: "Ph.D Program in Communication",
          short : "Ph.D Program in Communication",
          chinese_name : "傳播博",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=25",
          official_website_url: "https://ccphd.nccu.edu.tw/",
        },
        {
          id: "501",
          name: "Department of English",
          short : "English",
          chinese_name : "英文系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=26",
          official_website_url: "https://english.nccu.edu.tw/",
        },
        {
          id: "502",
          name: "Department of Arabic Language and Culture",
          short : "Arabic Language and Culture",
          chinese_name : "阿語系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=27",
          official_website_url: "https://arabic.nccu.edu.tw/",
        },
        {
          id: "504",
          name: "Department of Slavic Languages and Literatures",
          short : "Slavic Languages and Literatures",
          chinese_name : "斯語系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=28",
          official_website_url: "https://slavic.nccu.edu.tw/",
        },
        {
          id: "506",
          name: "Department of Japanese",
          short : "Japanese",
          chinese_name : "日語系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=30",
          official_website_url: "https://japanese.nccu.edu.tw/",
        },
        {
          id: "507",
          name: "Department of Korean Language and Culture",
          short : "Korean Language and Culture",
          chinese_name : "韓文系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=31",
          official_website_url: "https://korean.nccu.edu.tw/",
        },
        {
          id: "508",
          name: "Department of Turkish Language and Culture",
          short : "Turkish Language and Culture",
          chinese_name : "土語系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=32",
          official_website_url: "https://turkish.nccu.edu.tw/",
        },
        {
          id: "509",
          name: "Department of European Languages and Cultures",
          short : "Department of European Languages and Cultures",
          chinese_name : "歐文學系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=33",
          official_website_url: "https://european.nccu.edu.tw/",
        },
        {
          id: "510",
          name: "College of Foreign Languages",
          short : "College of Foreign Languages",
          chinese_name : "外院學士",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=34",
          official_website_url: "https://foreign.nccu.edu.tw/",
        },    
        {
          id: "560",
          name: "Master Program in Middle Eastern and Central Asian Studies",
          short : "Master Program in Middle Eastern and Central Asian Studies",
          chinese_name : "中東亞學程",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=35",
          official_website_url: "https://mecas.nccu.edu.tw/",
        },
        {
          id: "510",
          name: "Program in Southeast Asian Languages and Cultures",
          short : "Program in Southeast Asian Languages and Cultures",
          chinese_name : "東南亞語言與文化學士學位學程",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=36",
          official_website_url: "https://sealc.nccu.edu.tw/",
        },
        {
          id: "555",
          name: "Graduate Institute of Linguistics",
          short : "Graduate Institute of Linguistics",
          chinese_name : "語言所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=37",
          official_website_url: "https://ling.nccu.edu.tw/",
        },
        {
          id: "951",
          name: "M.A.Program in TESOL for In-Service Teachers",
          short : "M.A.Program in TESOL for In-Service Teachers",
          chinese_name : "英教碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=38",
          official_website_url: "https://etma.nccu.edu.tw/",
        },
        {
          id: "5T1",
          name: "Foreign Languages Center",
          short : "Foreign Languages Center",
          chinese_name : "外文中心",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=39",
          official_website_url: "https://flc.nccu.edu.tw/",
        },
        {
          id: "601",
          name: "Department of Law",
          short : "Law",
          chinese_name : "法律系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=40",
          official_website_url: "http://www.law.nccu.edu.tw/",
        },
        {
          id: "600",
          name: "College of Law",
          short : "Law",
          chinese_name : "法學院",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=41",
          official_website_url: "http://www.law.nccu.edu.tw/",
        },
        {
          id: "961",
          name: "Executive Master of Laws Program",
          short : "Executive Master of Laws Program",
          chinese_name : "法碩專",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=42",
          official_website_url: "http://www.law.nccu.edu.tw/zh_tw/departments/master/Special_introduction",
        },
        {
          id: "604",
          name: "Graduate Institute of Law and Interdisciplinary Studies",
          short : "Graduate Institute of Law and Interdisciplinary Studies",
          chinese_name : "法科碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=43",
          official_website_url: "http://www.law.nccu.edu.tw/zh_tw/departments/Inter_discipline/Law_Institute",
        },
        {
          id: "701",
          name: "Department of Mathematical Sciences",
          short : "Mathematical Sciences",
          chinese_name : "應數系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=44",
          official_website_url: "https://math.nccu.edu.tw/",
        },
        {
          id: "702",
          name: "Department of Psychology",
          short : "Psychology",
          chinese_name : "心理系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=45",
          official_website_url: "https://psy.nccu.edu.tw/",
        },
        {
          id: "782",
          name: "Bachelor of Science(B.S.) Program in Electrophysics",
          short : "Bachelor of Science(B.S.) Program in Electrophysics",
          chinese_name : "電物學程",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=46",
          official_website_url: "https://ephys.nccu.edu.tw/",
        },
        {
          id: "705",
          name: "Graduate Institute of Applied Physics",
          short : "Graduate Institute of Applied Physics",
          chinese_name : "應物所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=47",
          official_website_url: "https://phys.nccu.edu.tw/",
        },
        {
          id: "754",
          name: "Graduate Institute of Neuroscience",
          short : "Graduate Institute of Neuroscience",
          chinese_name : "神科所",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=48",
          official_website_url: "https://in.nccu.edu.tw/",
        },
        {
          id: "172",
          name: "MA Program of Counseling and Guidance",
          short : "MA Program of Counseling and Guidance",
          chinese_name : "輔諮碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=49",
          official_website_url: "https://mpcg.nccu.edu.tw/",
        },
        {
          id: "703",
          name: "Department of Computer Science",
          short : "Computer Science",
          chinese_name : "資科系",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=50",
          official_website_url: "https://www.cs.nccu.edu.tw/web/index/index.jsp",
        },
        {
          id: "781",
          name: "Undergraduate Program in Digital Content and Technologies",
          short : "Undergraduate Program in Digital Content and Technologies",
          chinese_name : "數位學程",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=51",
          official_website_url: "https://dct.nccu.edu.tw/",
        },
        {
          id: "ZA0",
          name: "College of Informatics",
          short : "College of Informatics",
          chinese_name : "資訊學院",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=3",
          official_website_url: "https://www.cs.nccu.edu.tw/web/index/index.jsp",
        },
        {
          id: "971",
          name: "Master Program in Computer Science",
          short : "Master Program in Computer Science",
          chinese_name : "資專碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=4",
          official_website_url: "https://www.cs.nccu.edu.tw/web/about/about.jsp?cp_no=CP1558925060196",
        },
        {
          id: "761",
          name: "Social Networks and Human-Centered Computing (SNHCC)",
          short : "Social Networks and Human-Centered Computing (SNHCC)",
          chinese_name : "群智博",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=5",
          official_website_url: "https://tigp.sinica.edu.tw/",
        },
        {
          id: "Z23",
          name: "International College of Innovation",
          short : "International College of Innovation",
          chinese_name : "創國學院",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=6",
          official_website_url: "https://ici.nccu.edu.tw/",
        },
        {
          id: "ZU1",
          name: "BA in Global Governance",
          short : "BA in Global Governance",
          chinese_name : "創新國際事務學院",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=7",
          official_website_url: "https://ici.nccu.edu.tw/",
        },
        {
          id: "1201",
          name: "Center for Creativity and Innovation Studies",
          short : "Center for Creativity and Innovation Studies",
          chinese_name : "創新創造力研究中心",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=8",
          official_website_url: "http://www.ccis.nccu.edu.tw/",
        },
        {
          id: "1202",
          name: "Office of Academic Affairs Center of General Education",
          short : "Office of Academic Affairs Center of General Education",
          chinese_name : "教務處通識教育中心",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=9",
          official_website_url: "https://aca.nccu.edu.tw/zh/%E9%80%9A%E8%AD%98%E6%95%99%E8%82%B2%E4%B8%AD%E5%BF%83",
        },
        {
          id: "1203",
          name: "International Relation(Common Course)",
          short : "International Relation(Common Course)",
          chinese_name : "國關通",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=10",
          official_website_url: "https://iir.nccu.edu.tw/",
        },
        {
          id: "1204",
          name: "Program in Bio-technology Management",
          short : "Program in Bio-technology Management",
          chinese_name : "生科程碩",
          logo_img_url: "https://source.unsplash.com/random/200x200?sig=81",
          official_website_url: "https://tiipm.nccu.edu.tw/zh_tw/BMP",
        },
    ];
  
  export const departmentsData=[
    {
      id: "101",
      name: "Department of Chinese Literature",
      short : "CHINESE",
      chinese_name : "中文系",
      logo_img_url: "https://source.unsplash.com/random/200x200?sig=1",
          official_website_url: "",
    },
    {
      id: "103",
      name: "Department of History",
      short : "HISTORY",
      chinese_name : "歷史系",
    },
    {
      id: "104",
      name: "Department of Philosophy",
      short : "PHILOSOPHY",
      chinese_name : "哲學系",
    },
    {
      id: "102",
      name:"Department of Education",
      short : "EDUACATION",
      chinese_name : "教育系",
    },
    {
      id: "202",
      name: "Department of Political Science",
      short : "ENGLISH",
      chinese_name : "政治系",
    },
    {
      id: "204",
      name: "Department of Sociology",
      short : "ARABIC",
      chinese_name : "社會系",
    },
    {
      id: "205",
      name: "Department of Public Finance",
      short : "FINANCE",
      chinese_name : "財政系",
    },
    {
      id: "206",
      name: "Department of Public Administration",
      short : "JAPANESE",
      chinese_name : "公行系",
    },
    {
      id: "207",
      name: "Department of Land Economics",
      short : "KOREA",
      chinese_name : "地政系",
    },
    {
      id: "208",
      name: "Department of Economics",
      short : "KOREA",
      chinese_name : "經濟系",
    },
    {
      id: "209",
      name: "Department of Ethnology",
      short : "KOREA",
      chinese_name : "民族系",
    },
    {
      id: "203",
      name:"Department of Diplomacy",
      short : "LAW",
      chinese_name : "外交系",
    },
    {
      id: "301",
      name: "Department of International Business",
      short : "ENGLISH",
      chinese_name : "國貿系",
    },
    {
      id: "302",
      name: "Department of Money and Banking",
      short : "ARABIC",
      chinese_name : "金融系",
    },
    {
      id: "303",
      name: "Department of Accounting",
      short : "FINANCE",
      chinese_name : "會計系",
    },
    {
      id: "304",
      name: "Department of Statistics",
      short : "Department of Statistics",
      chinese_name : "統計系",
    },
    {
      id: "305",
      name: "Department of Business Administration",
      short : "Department of Business Administration",
      chinese_name : "企管系",
    },
    {
      id: "306",
      name: "Department of Management Information Systems",
      short : "Department of Management Information Systems",
      chinese_name : "資管系",
    },
    {
      id: "307",
      name: "Department of Finance",
      short : "Department of Finance",
      chinese_name : "財管系",
    },
    {
      id: "308",
      name: "Department of Risk Management and Insurance",
      short : "Department of Risk Management and Insurance",
      chinese_name : "風管系",
    },
    {
      id: "401",
      name: "Department of Journalism",
      short : "Department of Journalism",
      chinese_name : "新聞系",
    },
    {
      id: "402",
      name: "Department of Advertising",
      short : "Department of Advertising",
      chinese_name : "廣告系",
    },
    {
      id: "403",
      name: "Department of Radio & Television",
      short : "Department of Radio & Television",
      chinese_name : "廣電系",
    },
    {
      id: "404",
      name: "ENGLISH",
      short : "ENGLISH",
      chinese_name : "傳播學程",
    },
    {
      id: "501",
      name: "Department of English",
      short : "Department of English",
      chinese_name : "英文系",
    },
    {
      id: "502",
      name: "Department of Arabic Language and Culture",
      short : "Department of Arabic Language and Culture",
      chinese_name : "阿語系",
    },
    {
      id: "504",
      name: "Department of Slavic Languages and Literatures",
      short : "Department of Slavic Languages and Literatures",
      chinese_name : "斯語系",
    },
    {
      id: "508",
      name: "Department of Arabic Language and Culture                                                                                             ",
      short : "Department of Arabic Language and Culture                                                                                             ",
      chinese_name : "土語系",
    },
    {
      id: "601",
      name: "College of Law",
      short : "LAW",
      chinese_name : "法律系",
    },
    {
      id: "506",
      name: "Department of Japanese",
      short : "Department of Japanese",
      chinese_name : "日語系",
    },
    {
      id: "507",
      name: "Department of Korean Language and Culture",
      short : "Department of Korean Language and Culture",
      chinese_name : "韓文系",
    },
    {
      id: "601",
      name: "Department of Law",
      short : "LAW",
      chinese_name : "法律系",
    },
    {
      id: "602",
      name: "College of Law",
      short : "LAW",
      chinese_name : "法學院",
    },
    {
      id: "701",
      name: "Department of Mathematical Sciences",
      short : "Mathematical Sciences",
      chinese_name : "應數系",
    },
    {
      id: "702",
      name: "Department of Psychology",
      short : "Department of Psychology",
      chinese_name : "心理系",
    },
    {
      id: "703",
      name: "Department of Computer Science",
      short : "Department of Computer Science",
      chinese_name : "資科系",
    }
]

export const professors =
[
    {
        "Professor": "左瑞麟",
        "department":"703",
        "type": "教授",
        "email": "raylin@cs.nccu.edu.tw",
        "extension_number": "62328",
        "education": "日本筑波大學 系統與資訊工程博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/islab/advisor.html",
        "lab_website_url": "https://www.cs.nccu.edu.tw/islab/index.html"
    },
    {
        "Professor": "江玥慧",
        "department":"703",
        "type": "助理教授",
        "email": "yhchiang@cs.nccu.edu.tw",
        "extension_number": "67509",
        "education": "美國德州大學奧斯汀總校區 學習科技博士",
        "person_website_url": "https://sites.google.com/g.nccu.edu.tw/yhchiang/"
    },
    {
        "Professor": "李蔡彥",
        "department":"703",
        "type": "教授 兼創新與創造力中心主任",
        "email": "li@cs.nccu.edu.tw",
        "extension_number": "67642",
        "education": "美國史丹福大學 機械工程博士",
        "person_website_url": "http://www3.nccu.edu.tw/~li/",
        "lab_website_url": "http://imlab.cs.nccu.edu.tw/IMWeb/"
    },
    {
        "Professor": "沈錳坤",
        "department":"703",
        "type": "教授",
        "email": "mkshan@cs.nccu.edu.tw",
        "extension_number": "67622",
        "education": "國立交通大學 電腦科學博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~mkshan/",
        "lab_website_url": "https://www.cs.nccu.edu.tw/~mkshan/"
    },
    {
        "Professor": "邱淑怡",
        "department":"703",
        "type": "助理教授",
        "email": "sichiu@nccu.edu.tw",
        "extension_number": "88112",
        "education": "國立政治大學 資訊科學系博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~sichiu/index.htm"
    },
    {
        "Professor": "紀明德",
        "department":"703",
        "type": "副教授",
        "email": "mtchi@cs.nccu.edu.tw",
        "extension_number": "62773",
        "education": "國立成功大學 資訊工程博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~mtchi/",
        "lab_website_url": "http://www.cs.nccu.edu.tw/~mtchi/"
    },
    {
        "Professor": "胡毓忠",
        "department":"703",
        "type": "教授兼電子計算機中心主任與資訊學院院長",
        "email": "jong@g.nccu.edu.tw",
        "extension_number": "67620",
        "education": "美國密蘇里大學 電腦科學博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~jong/JongWebPage/MainSlides.html",
        "lab_website_url": "http://ent.cs.nccu.edu.tw/drupal/"
    },
    {
        "Professor": "郭桐惟",
        "department":"703",
        "type": "助理教授",
        "email": "twkuo@cs.nccu.edu.tw",
        "extension_number": "67621",
        "education": "國立清華大學 資訊工程學博士",
        "person_website_url": "https://sites.google.com/site/tungweikuo/",
        "lab_website_url": "https://sites.google.com/site/tungweikuo/"
    },
    {
        "Professor": "曾一凡",
        "department":"703",
        "type": "助理教授",
        "email": "yftseng@cs.nccu.edu.tw",
        "extension_number": "67514",
        "education": "國立中山大學資訊工程博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~yftseng/index.html",
        "lab_website_url": "https://www.cs.nccu.edu.tw/~yftseng/index.html"
    },
    {
        "Professor": "張宏慶",
        "department":"703",
        "type": "副教授",
        "email": "jang@cs.nccu.edu.tw",
        "extension_number": "67639",
        "education": "美國伊利諾大學 電腦科學博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~jang/welcome.html",
        "lab_website_url": "http://www.cs.nccu.edu.tw/~jang/lab-3.htm"
    },
    {
        "Professor": "張家銘",
        "department":"703",
        "type": "助理教授",
        "email": "chang.jiaming@gmail.com",
        "extension_number": "88137",
        "education": "西班牙 基因調控研究中心與龐培法布拉大學 生物資訊博士",
        "person_website_url": "http://www.changlabtw.com/",
        "lab_website_url": "http://www.changlabtw.com/"
    },
    {
        "Professor": "彭彥璁",
        "department":"703",
        "type": "助理教授",
        "email": "ytpeng@cs.nccu.edu.tw",
        "extension_number": "67544",
        "education": "美國加州大學聖地牙哥分校 電機與電腦工程博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~ytpeng/",
        "lab_website_url": "https://www.cs.nccu.edu.tw/~ytpeng/"
    },
    {
        "Professor": "廖文宏",
        "department":"703",
        "type": "副教授兼在職專班執行長",
        "email": "whliao@gmail.com",
        "extension_number": "62028",
        "education": "美國德州大學奧斯汀總校區 電機與電腦工程博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~whliao/",
        "lab_website_url": "https://www.cs.nccu.edu.tw/~whliao/indexc.html"
    },
    {
        "Professor": "廖峻鋒",
        "department":"703",
        "type": "副教授",
        "email": "cfliao@cs.nccu.edu.tw",
        "extension_number": "62297",
        "education": "國立台灣大學 資訊工程博士",
        "person_website_url": "http://cfliao.net/",
        "lab_website_url": "http://selab.nccu.edu.tw/"
    },
    {
        "Professor": "蔡子傑",
        "department":"703",
        "type": "教授",
        "email": "ttsai@cs.nccu.edu.tw",
        "extension_number": "62265",
        "education": "美國加州大學 電腦科學博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~ttsai/",
        "lab_website_url": "https://www.cs.nccu.edu.tw/~ttsai/"
    },
    {
        "Professor": "蔡欣叡",
        "department":"703",
        "type": "助理教授",
        "email": "hsnuhrt@gmail.com",
        "extension_number": "62969",
        "education": "國立台灣大學 資訊工程博士",
        "person_website_url": "https://hsnuhrt.github.io/",
        "lab_website_url": "https://hsnuhrt.github.io/"
    },
    {
        "Professor": "蔡銘峰",
        "department":"703",
        "type": "副教授（中研院資創中心合聘副研究員）",
        "email": "mftsai@cs.nccu.edu.tw",
        "extension_number": "62558",
        "education": "國立台灣大學 資訊工程博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~mftsai/",
        "lab_website_url": "http://www.cs.nccu.edu.tw/~mftsai/"
    },
    {
        "Professor": "劉吉軒",
        "department":"703",
        "type": "教授",
        "email": "liujs@nccu.edu.tw",
        "extension_number": "62264",
        "education": "美國卡內基美隆大學 機器人學博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~jsliu/",
        "lab_website_url": "http://www.cs.nccu.edu.tw/~starlab/"
    },
    {
        "Professor": "劉昭麟",
        "department":"703",
        "type": "特聘教授(系主任)",
        "email": "chaolin@g.nccu.edu.tw",
        "extension_number": "67511",
        "education": "美國密西根大學 資訊科學暨工程博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/~chaolin/",
        "lab_website_url": "http://www.cs.nccu.edu.tw/~mig/cmig.html"
    },
    {
        "Professor": "謝佩璇",
        "department": "703",
        "type": "副教授",
        "email": "pei.peace@gmail.com",
        "extension_number": "62189",
        "education": "美國賓州州立大學 教學系統博士",
        "person_website_url": "https://www.cs.nccu.edu.tw/web/team/team_in.jsp?mp_no=MP1568085304243"
    }
]