FROM node
WORKDIR /usr/src/app
COPY ["package.json", "npm-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN apt-get update && apt-get install -y vim
RUN npm install pm2 -g
RUN pm2 install pm2-logrotate
RUN pm2 set pm2-logrotate:max_size 100M
RUN pm2 set pm2-logrotate:compress true
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 59001
# RUN chown -R node /usr/src/app
# USER node
CMD ["pm2-runtime", "start", "ecosystem.config.cjs"]
